repos:
  - repo: local
    hooks:
      - id: lint-fix
        name: Run linting and formatting
        entry: make lint-fix
        language: system
        pass_filenames: false
        always_run: true
      - id: test
        name: Run tests
        entry: make test
        language: system
        pass_filenames: false
        always_run: true