[project]
name = "intent-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.5",
    "httpx>=0.27.2",
    "mlflow>=2.18.0",
    "polars>=1.14.0",
    "ruff>=0.8.0",
    "torch>=2.5.1",
    "transformers>=4.46.3",
    "uvicorn>=0.32.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]
